---
- name: Install Java 8
  yum: name=java-1.8.0-openjdk.x86_64 state=latest

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: 
    url: http://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.6/bin/apache-tomcat-9.0.6.tar.gz
    dest: /opt/apache-tomcat-9.0.6.tar.gz
    timeout: 120

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-9.0.6.tar.gz -C /opt/ creates=/opt/apache-tomcat-9.0.6

- name: Symlink install directory
  file: src=/opt/apache-tomcat-9.0.6 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Install Tomcat Service
  copy: src=tomcat9.service dest=/etc/systemd/system/tomcat9.service

- name: Start Tomcat
  service: name=tomcat9 state=started enabled=yes
  ignore_errors: True

- name: Deploy Application
  copy: src=petclinic.war dest=/usr/share/tomcat/webapps
  
- name: Stop Tomcat
  service: name=tomcat9 state=stopped
  
- name: Start Tomcat
  service: name=tomcat9 state=started

